### ISSUE TITLE
Need to research and employ Kafka topics

### ISSUE THREAD

**Issue by tfplenum** [tfplenum/rock#1]
<a href="https://github.com/grantcurell"><img src="https://avatars2.githubusercontent.com/u/1595564?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [grantcurell](https://github.com/grantcurell)**
_Saturday Dec 23, 2017 at 22:57 GMT_
_Originally opened as https://github.com/grantcurell/rock/issues/3_

----

Rock build uses Kafka topics and we still have the leftover handlers. Need to look into them and either delete or employ them.

These are the handlers that were unused in the previous rock build:
```
#    - name: create kafka bro topic
#      command: >
#        /opt/kafka/bin/kafka-topics.sh
#           --zookeeper 127.0.0.1:2181
#           --create
#           --replication-factor 1
#           --topic bro-raw
#           --partitions 1
#
#    - name: create kafka suricata topic
#      command: >
#        /opt/kafka/bin/kafka-topics.sh
#           --zookeeper 127.0.0.1:2181
#           --create
#           --replication-factor 1
#           --topic suricata-raw
#           --partitions 1
#
#    - name: create kafka fsf topic
#      command: >
#        /opt/kafka/bin/kafka-topics.sh
#           --zookeeper 127.0.0.1:2181
#           --create
#           --replication-factor 1
#           --topic fsf-raw
#           --partitions 1
```

**Comment by grantcurell** [comment]
<a href="https://github.com/littletone2002"><img src="https://avatars3.githubusercontent.com/u/10156672?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [littletone2002](https://github.com/littletone2002)**
_Friday Dec 29, 2017 at 19:42 GMT_

----

If you want to understand Kafka, start here https://www.youtube.com/watch?v=aJuo_bLSW6s
In fact, I think this video should be required viewing for all engineers to understand the problems in big data and processing.

**Comment by kwilson7770** [comment]
Related issue: #1

**Comment by grantcurell** [comment]
I have finished this.
