### ISSUE TITLE
Fix the code in generate defaults

### ISSUE THREAD

**Issue by tfplenum** [tfplenum/rock#11]
<a href="https://github.com/grantcurell"><img src="https://avatars2.githubusercontent.com/u/1595564?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [grantcurell](https://github.com/grantcurell)**
_Sunday Dec 31, 2017 at 19:51 GMT_
_Originally opened as https://github.com/grantcurell/rock/issues/30_

----

The code in generate defaults currently does not run. We need to clean it up and also improve the interface detection.

**Comment by grantcurell** [comment]
<a href="https://github.com/jahatfi"><img src="https://avatars2.githubusercontent.com/u/12942571?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jahatfi](https://github.com/jahatfi)**
_Sunday Dec 31, 2017 at 23:10 GMT_

----

Done; I've submitted the pull request

**Comment by grantcurell** [comment]
<a href="https://github.com/grantcurell"><img src="https://avatars2.githubusercontent.com/u/1595564?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [grantcurell](https://github.com/grantcurell)**
_Monday Jan 01, 2018 at 22:54 GMT_

----

There seems to be a bug. I get duplicate interface names when I run the code now. For example I'll get some of the usual interface names, but then I get eth1 twice.

**Comment by grantcurell** [comment]
<a href="https://github.com/jahatfi"><img src="https://avatars2.githubusercontent.com/u/12942571?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jahatfi](https://github.com/jahatfi)**
_Tuesday Jan 02, 2018 at 18:46 GMT_

----

If duplicate interfaces is the only issue, try filtering the list with unique: e.g.
rock_monifs: '{% set rock_monifs = rock_monifs|default([]) + [item] %}{{ rock_monifs|list|unique }}"
I'd test it myself but I never had an issue with duplicate interfaces.

**Comment by dwharve** [comment]
Removed the need for generate defaults. Issue resolved.
