### ISSUE TITLE
We should examine eliminating the JSON _source from elasticsearch

### ISSUE THREAD

**Issue by grantcurell** [tfplenum/rock#116]
![capture](https://user-images.githubusercontent.com/35169230/35106852-f6365a04-fc34-11e7-9ece-442ebc4e37a4.PNG)

This may not be needed for our build.

**Comment by mrmills93** [comment]
I originally thought this field would be needed. After further research, for our use case it would only be used if for some reason we would have to reindex pre existing data. As I can not see a time when we would need to do that, i will disable the field.
