### ISSUE TITLE
We hardcoded the name of the server in kibana defaults

### ISSUE THREAD

**Issue by grantcurell** [tfplenum/rock#135]
We hard coded rockserver1.lan:9200 in Kibana's defaults. We need to replace this with something more intelligent.

**Comment by GonzoVC** [comment]
@mrmills93 fixed this issue by added the environment variable " - ELASTICSEARCH_URL="{{ es_url }}" within the kibana-compose.yml file.

under the kibana/defaults/main.yml, es_url variable resolves to "http://rock-elasticsearch:9200"

Closing Issue.
