### ISSUE TITLE
Enable and start broctl task fails

### ISSUE THREAD

**Issue by tfplenum** [tfplenum/rock#14]
<a href="https://github.com/grantcurell"><img src="https://avatars2.githubusercontent.com/u/1595564?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [grantcurell](https://github.com/grantcurell)**
_Monday Jan 01, 2018 at 23:27 GMT_
_Originally opened as https://github.com/grantcurell/rock/issues/35_

----

During the first run of the playbook, the Enable and start broctl task fails. Resolving the issue is as simple as running `broctl`, `deploy`, and then `ansible-playbook site.yml --start-at-task="Enable and start broctl"`. It seems broctl is properly running, but the service fails for some reason or another.

**Comment by grantcurell** [comment]
Looks like boosta took care of this one.
