### ISSUE TITLE
We need to ensure elasticsearch has correct JVM settings

### ISSUE THREAD

**Issue by grantcurell** [tfplenum/rock#141]
See: https://www.elastic.co/guide/en/elasticsearch/reference/current/heap-size.html

**Edit**

I'm going to leave this open. We need to do this for each instance of Elasticsearch for the hardware optimization process. Opening another issue for automatically detecting this.

**Comment by JReyna** [comment]
Settings were already set in es_mem variable declaration to give elastic half the memory up to 31 GB.  This agrees with recommendations from elastic.co link above.  Variable es_mem is declared twice in playbooks/group_vars/servers/servers.yml and playbooks/roles/elasticsearch/defaults/mainl.yml.  Configuration is set in es-jvm.options.j2 file.

**Comment by grantcurell** [comment]
I have added preflight checks in Elasticsearch to verify this is the case.
