### ISSUE TITLE
Determine if we need to change DNS cache settings on JVM

### ISSUE THREAD

**Issue by grantcurell** [tfplenum/rock#145]
See: https://www.elastic.co/guide/en/elasticsearch/reference/current/networkaddress-cache-ttl.html

**Comment by JReyna** [comment]
Old file of es-jvm.options.j2 in elasticsearch_old role has been replaced with es-master.yml.j2 template.  The ES_JAVA_OPTS only sets the memory options but can include java options for -Dnetworkaddress.cache.ttl  and -Dnetworkaddress.cache.negative.tt if needed for multiple DNS configured networks.

**Comment by grantcurell** [comment]
Do we need that in our current build?
