### ISSUE TITLE
We need different NIC settings for Bro, Suricata, and PCAP

### ISSUE THREAD

**Issue by grantcurell** [tfplenum/rock#149]
Right now, everything is set to use rock_monifs. This should be a default setting, but should be overridden by more specific interfaces for each of three.

**Edit**

Requirements
- Interfaces for Bro, Suricata, and Moloch must be configured on a per sensor basis
- This must be accomplished through user configurable values in the inventory file

End State Testing
- Bro, Suricata, and Moloch on each sensor should listen on the appropriate interface as defined by the Ansible inventory file. Anywhere the interface is used within the various templates should be correspondingly updated.

**Comment by grantcurell** [comment]
The settings need to be moved to the inventory settings and the prompt in sensor-common should be removed.

**Comment by neutron132** [comment]
Will do.

**Comment by neutron132** [comment]
Putting on hold until Kubernetes is complete.

**Comment by dwharve** [comment]
This has been accomplished using a combination of configmaps and confd with a redis backend. Only moloch has been configured so far.

**Comment by grantcurell** [comment]
We decided this is no longer necessary / does not have a use case.
