### ISSUE TITLE
Create anti-affinity rules per pod

### ISSUE THREAD

**Issue by grantcurell** [tfplenum/rock#184]
Dcode: for elasticsearch and kafka, in order to scale, you ideally want to use anti-affinity rules per pod...so you would spin up an ES pod per ES node and they would all run on different hosts

[21:21]
I don't think the affinity rules are critical up front, but that's what's needed...same for kafka

regardless, there are rules in the scheduler that can do that...I think instead of anti-affinity, you set a "repel" setting...which means they could coexist on the same node, but prefer not to

**Comment by dwharve** [comment]
The following affinity rules are in place:
Kafka requires a sensor without a Kafka pod running to be allocated
Bro requires a sensor without a bro pod running to be allocated
Suricata requires a sensor without a suricata pod running to be allocated
Moloch requries a sensor without a moloch pod running to be allocated 
ES-master requires a server with double es_mem of memory free to be allocated

**Comment by Prodian0013** [comment]
Fixed in 9a67297
