### ISSUE TITLE
Port Suricata to Kubernetes

### ISSUE THREAD

**Issue by grantcurell** [tfplenum/rock#188]
I wrote code for setting up a Suricata container available at: https://github.com/tfplenum/rock-containers/tree/curell-suricata

I did not complete it because of a bug in Ansible Container. There is a fix in progress and you can check the status [here](https://github.com/ansible/ansible-container/pull/719). You can see a description of the issue [here](https://github.com/ansible/ansible-container/issues/865).

What still needs to be done:
- The container itself should be good to go once that fix in Ansible Container is made. However, no testing has been done. Need to complete testing on:
  - Suricata itself
  - Pulled pork
- Integrate the container into Kubernetes. Right now all the role data is from the old single node build. We need to move it over to Kubernetes. You can use Bro as a template.

Requirements:
- Container should operate appropriately and run Suricata just like it would run on bare metal. See the Bro container for a point of reference.

**Comment by dwharve** [comment]
Completed
Container available at tfplenum/suricata:1.0
Utilizes filebeats to ship logs to kafka
