### ISSUE TITLE
Build Elasticsearch Curator

### ISSUE THREAD

**Issue by tfplenum** [tfplenum/rock#19]
<a href="https://github.com/grantcurell"><img src="https://avatars2.githubusercontent.com/u/1595564?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [grantcurell](https://github.com/grantcurell)**
_Wednesday Jan 03, 2018 at 16:06 GMT_
_Originally opened as https://github.com/grantcurell/rock/issues/41_

----

We need to convert the es_cleanup.sh to a build of elasticsearch curator. Primarily, it needs to clean up indexes after X period of time. Currently that time period is 30 days.

**Comment by grantcurell** [comment]
Needs to be tested, but is now part of the devel branch.

**Comment by RuriRurouni** [comment]
Testing complete. Curator is now cleaning up indices at 12:01 AM every day.
