### ISSUE TITLE
Configure filebeat to round robin based on multiple elasticsearch servers

### ISSUE THREAD

**Issue by tfplenum** [tfplenum/rock#20]
<a href="https://github.com/grantcurell"><img src="https://avatars2.githubusercontent.com/u/1595564?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [grantcurell](https://github.com/grantcurell)**
_Wednesday Jan 03, 2018 at 16:26 GMT_
_Originally opened as https://github.com/grantcurell/rock/issues/42_

----

Right now our configuration only sends to one Elasticsearch server. We want to round robin by default across multiple elasticsearch servers if they are available.

**Comment by todd8152** [comment]
The current filebeat configuration sends suricata and fsf logs to kafka on the localhost.  Logstash will pull from kafka.  I don't think any changes are necessary at this time.
