### ISSUE TITLE
Promiscuous mode is not turned on after install

### ISSUE THREAD

**Issue by kwilson7770** [tfplenum/rock#200]
I noticed that the monitoring interface selected is not being set to promiscuous mode by default. I had to manually set it with this command:
ip link set dev ens34 promisc on

After restarting the machine, promsic mode was turned on through the ifup-local script that was installed

**Comment by JReyna** [comment]
# The following code will put interface en34 into promiscuous mode
- hosts: sensor
  vars:
    interface: "ens34"
  tasks:
  - name: Ensure promiscuous mode is on
    command: ip link set dev {{interface}} promisc off

**Comment by grantcurell** [comment]
Is this still an issue or can it be closed?

**Comment by grantcurell** [comment]
Not able to reproduce.
