### ISSUE TITLE
Lighttpd configuration needs completed

### ISSUE THREAD

**Issue by tfplenum** [tfplenum/rock#22]
<a href="https://github.com/Duckmanjbr"><img src="https://avatars3.githubusercontent.com/u/19156336?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Duckmanjbr](https://github.com/Duckmanjbr)**
_Thursday Jan 04, 2018 at 21:19 GMT_
_Originally opened as https://github.com/grantcurell/rock/issues/49_

----

Lighttpd is installed and running.  However, lighttpd is not configured to work as a proxy.  The proxy must be configured to forward requests to their correct container.  For example, the proxy is listening on port 80 of the host.  All other containers are running behind the proxy on their perspective ports.  The proxy must be configured to to forward requests to the correct container.  URL-> dockervm/kibana should be forwarded to host=kibana/port=5601.  URL-> dockervm/portainer should be forwarded to host=portainer/port=9000.

**Comment by kwilson7770** [comment]
Currently trying to rewrite the URI from /portainer/* to /* and then proxy the connection to a different server and it appears that a 12.5 year old bug might be preventing this from being a simple configuration...
https://redmine.lighttpd.net/issues/164

**Comment by kwilson7770** [comment]
Also, if anything on the back-end using HTTPS, then it won't work according to the docs
"lighttpd mod_proxy does not currently support SSL/TLS connections to the backend server"
https://redmine.lighttpd.net/projects/lighttpd/wiki/Docs_ModProxy

**Comment by kwilson7770** [comment]
Possible work arounds to 12.5 year old issue:
1) https://serverfault.com/questions/135770/rewrite-url-before-passing-to-proxy-lighttpd
2)
> Although I used this "double" proxy solution for many years, I searched for better solution.
> 
> Here is my new approach with lua/mod_magnet:
> 
> $HTTP["url"] =~ "^/webapp/" {
>   magnet.attract-raw-url-to = ( "/etc/lighttpd/lua/webapp.lua" )
>   proxy.server = ( "" => ("webapp" => ("host" => "127.0.0.1", "port" => 8008)))
> }
> and /etc/lighttpd/lua/webapp.lua:
> 
> lighty.env["request.uri"] = string.sub(lighty.env["request.uri"], string.len('/webapp/'))
> return
> This is very close to the original request ...
3)

> FYI: lighttpd 1.4.46 introduces proxy.header which performs limited URL-prefix rewriting. More info at [Docs_ModProxy](https://redmine.lighttpd.net/projects/lighttpd/wiki/Docs_ModProxy)

**Comment by kwilson7770** [comment]
Lighttpd is being replaced by HAProxy after a great deal of effort to get it to work. Closing
