### ISSUE TITLE
Need to add an option for remote sensor

### ISSUE THREAD

**Issue by grantcurell** [tfplenum/rock#263]
Right now, everything is set to cluster regardless of location on the system. We need to add an inventory argument for the sensors which says they operate remotely. This option should prevent all clustering on that sensor and make it so that its only outbound traffic is the elastic data.

**Comment by Prodian0013** [comment]
Remote Sensor Design:
- ansible:
    - instead of host var should there be a new group for remote sensors?
    - currently statefulset replicas is determined by number of hosts in the sensor group.
    - remote sensor will provide the same functionality in terms of deployed apps but will not be configured the same as a sensor.

- storage:
   - remote sensor will not provide ceph osd or mon to ceph pool
   - remote sensor will not use rbd storage class.
   - remote sensor will use hostPath volume.
   - can kubernetes determine volume based on node label? (dont think so separate templates might be required.)

- templates:
   -  should there be separate statefulset templates for clustered sensor and remote sensor?
   -  should remote sensor use a statefulset?

- node label:
   - create new node label for remote sensors?
   - ie: remote-sensor
