### ISSUE TITLE
Need to add a localhost install and remote install option for sensor and server

### ISSUE THREAD

**Issue by grantcurell** [tfplenum/rock#28]
This can be accomplished with the add_host ansible function and the extra-vars command line option. Add an add_host task and use when statements with something like when: localhost to dynamically add the localhost to the sensors or servers group as needed.

**Comment by grantcurell** [comment]
I've fixed the issue where running sensor or server runs everything in the branch grantcurell-elasticsearch (no I shouldn't have fixed it there). The solution now will work, however, when we switch to a multi-node configuration hosts in the inventory would run along side the local option which needs to be fixed.

**Comment by grantcurell** [comment]
Generate defaults will not work the way it is currently structured. I have a hack work around to make it work for testing at the moment, but it needs to be updated.

**Comment by dwharve** [comment]
Implemented multinode remote install and removed the need for generate defaults
