### ISSUE TITLE
SSH delayed connection

### ISSUE THREAD

**Issue by dwharve1** [tfplenum/rock#288]
SSH delays connection due to being unable to resolve host names via kube-dns.
Either change sshd config, or add a forwarder for kube-dns

**Comment by grantcurell** [comment]
Completed.

**Comment by grantcurell** [comment]
Up until now we have been using the control server for DNS. We need to move it to master and then have all machines use master for DNS. We also need to modify the kubernetes role to not add kubedns to everything. That should resolve this problem.

**Comment by grantcurell** [comment]
This can be closed out as soon as we fix the kubedns config file.
