### ISSUE TITLE
Need to add role dependencies

### ISSUE THREAD

**Issue by tfplenum** [tfplenum/rock#3]
<a href="https://github.com/grantcurell"><img src="https://avatars2.githubusercontent.com/u/1595564?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [grantcurell](https://github.com/grantcurell)**
_Tuesday Dec 26, 2017 at 14:59 GMT_
_Originally opened as https://github.com/grantcurell/rock/issues/9_

----

We have several roles, specifically for containers, which are dependent on docker. Ex: Harbor, Portainer, etc. These roles should list docker as a role dependency in accordance with: http://docs.ansible.com/ansible/latest/playbooks_reuse_roles.html#role-dependencies

**Comment by grantcurell** [comment]
<a href="https://github.com/jahatfi"><img src="https://avatars2.githubusercontent.com/u/12942571?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jahatfi](https://github.com/jahatfi)**
_Friday Dec 29, 2017 at 17:30 GMT_

----

I'll hold off on this until we (1 have all the roles add and (2 know exactly which ones depend on docker.  At that point, I can add the dependencies all at once and just do one pull.

**Comment by grantcurell** [comment]
<a href="https://github.com/grantcurell"><img src="https://avatars2.githubusercontent.com/u/1595564?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [grantcurell](https://github.com/grantcurell)**
_Friday Dec 29, 2017 at 20:13 GMT_

----

Sounds good!

**Comment by RuriRurouni** [comment]
Dependency files created in my repo; pull request sent.

**Comment by grantcurell** [comment]
Adding dependencies in the metadata causes a lot of problems so we are going to skip it.
