### ISSUE TITLE
We need to test logstash and integrate it with Elasticsearch 6

### ISSUE THREAD

**Issue by grantcurell** [tfplenum/rock#35]
- Make sure all the logs are ingested properly.

**Comment by todd8152** [comment]
Kibana dashboards should be a separate issue.  I'm currently working on the docker image for the latest version of Logstash.

**Comment by Duckmanjbr** [comment]
I agree w/ Todd.  Dashboards are a separate thing.

**Comment by mrmills93** [comment]
Made changes to the logstash config to send the data to the appropriate templates/indices. Need an official test to see if it works as expected though.

**Comment by grantcurell** [comment]
Completed after marathon programming session!
