### ISSUE TITLE
Update the Elasticsearch Service Check

### ISSUE THREAD

**Issue by grantcurell** [tfplenum/rock#44]
Right now the elasticsearch installation runs the following code to check if Elasticsearch is running:

```
- name: "Wait for Elasticsearch to become ready"
  wait_for: "host=localhost port=9200"
```

Until the proxy is working, this code will not work. It will need to be fixed to work with the proxy.

**Comment by dwharve** [comment]
Corrected Elasticsearch wait task to work with local/multinode and haproxy. However it is dependent on at least one server having the haproxy role
