### ISSUE TITLE
Initial Elasticsearch Clustering

### ISSUE THREAD

**Issue by grantcurell** [tfplenum/rock#47]
Requirements:

- Number of instances must be controlled through Ansible inventory file. Variable should overwrite value in elasticsearch/vars/main.yml. This is employed in the roles/elasticsearch/templates/es-master.yml.j2 file
- Clustering must occur during installation in a fully automated fashion without user intervention aside from editing the inventory file
- Elasticsearch must only run on server nodes

End State / Test:
- Check to make sure all specified nodes are up and running
- Make sure all indices are green for Bro, Suricata, and Moloch

Edit: Removed all old issue text.

**Comment by dwharve** [comment]
Configured haproxy to resolve this issue. On the server that has with_haproxy as true will load balance requests to it on 9200 to any server that has with_elasticsearch as true. If with_lighttpd is false then haproxy will also proxy requests to kibana, and portainer and enforce ssl with a self signed cert.

**Comment by grantcurell** [comment]
This is being done via Kubernetes.

**Comment by dwharve** [comment]
Elasticsearch is clustered and scalable via a Stateful Set in Kubernetes. I am currently finding a stability issue where Elasticsearch will create new clusters if a slave node comes up while the master node is overloaded. This prevents the slave from communicating with the master and assuming the master role.
