### ISSUE TITLE
Portainer needs security added

### ISSUE THREAD

**Issue by tfplenum** [tfplenum/rock#5]
<a href="https://github.com/grantcurell"><img src="https://avatars2.githubusercontent.com/u/1595564?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [grantcurell](https://github.com/grantcurell)**
_Friday Dec 29, 2017 at 16:26 GMT_
_Originally opened as https://github.com/grantcurell/rock/issues/16_

----

Once port 2375 is opened, we need to configure portainer to use certificates so that the port is not freely available to manipulation. Find a way to secure portainer container and then install certificates on sensor nodes so that portainer function is secured.

**Comment by grantcurell** [comment]
With the advent of Kubernetes we no longer need portainer.
