### ISSUE TITLE
We need to find a way to have containers output to usual log locations

### ISSUE THREAD

**Issue by grantcurell** [tfplenum/rock#63]
Currently containers maintain their logs internally and you must use `docker logs X` in order to get log output. We need to find a way to redirect this to the regular log file locations on the host.

**Comment by Duckmanjbr** [comment]
We're talking about configurations and software logs here right?  Not the actual docker logs?

**Comment by grantcurell** [comment]
Ya, basically whatever is usually in /var/logs/<THING>

**Comment by GonzoVC** [comment]
Pull request #107 submitted to implement a bind mount for Elasticsearch logs, as well as fixing some permission-based variables within the logstash role (it was setting the elastic using account as owner of the /var/log/logstash directory).

Elasticsearch Role
1. Added es_log_dir variable in defaults main.yml
2. Added "create elasticsearch log directory" task in tasks main.yml
3. Added volume bind mount in elasticsearch.compse.yml.j2
4. Modified numbered UID/GUID to read as variable for elasticsearch user/group

Logstash Role
1. Modified numbered UID/GUID to read as variable for elasticsearch user/group

Moving onto the remaining server docker containers:
Elastic
Logstash
Kibana
Portainer
Harbor
HAProxy

After server is done, I'll move onto the sensor docker containers:
Sensor Containers:
Khafka
Zookeeper
Filebeats

**Comment by GonzoVC** [comment]
After a few bug fixes within the code and merging with the latest changes to devel:

Running playbook with --limit "server": Success
Running playbook with --limit "sensor": Success
Running playbook for both "server" and sensor" on a fresh VM: Success

Reference Pull Request: https://github.com/tfplenum/rock/pull/126
