### ISSUE TITLE
We need to configure metricbeat to monitor system performance

### ISSUE THREAD

**Issue by grantcurell** [tfplenum/rock#91]
Requirements:

Metricbeat must run on all nodes which run Docker
Import the appropriate Elasticsearch-built Metricbeat dashboards
End State Test:

Metricbeat dashboards populate with data from each of the monitored nodes

**Comment by Duckmanjbr** [comment]
Thoughts on how you want this?  Are you thinking only one beat to monitor system performance or are you thinking beats to monitor all these individual services?

**Comment by grantcurell** [comment]
At first, I'm thinking just the system performance or whatever the default is. I'm really not sure how little or much work this is. If it's easy to have it also monitor system services then all the better.

**Comment by todd8152** [comment]
It gets complicated when you want a container to monitor the host OS and other containers.  Lets keep it simple and just install the RPM.  We definitely need to 'tune' metricbeat.  It collects a lot of data by default but we can limit it to the processes and containers we want to keep an eye on.  We can also use it to monitor the overall CPU, RAM, Disk space and packet loss on the monitor interface for sensors.

**Comment by grantcurell** [comment]
When this is complete, it will need to be migrated to kubernetes.

**Comment by setalias** [comment]
this is complete and has been migrated to kubernetes.  waiting for kube / logstash to be g2g so can run  full tests.

**Comment by grantcurell** [comment]
Requirements:
- Metricbeat must run on all nodes which run Docker
- Import the appropriate Elasticsearch-built Metricbeat dashboards

End State Test:
- Metricbeat dashboards populate with data from each of the monitored nodes

**Comment by grantcurell** [comment]
This solution needs to be tested with the rest of the system

**Comment by grantcurell** [comment]
Finished this up.
